version: '3.9'

services:
  grafiles-mongo:
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=diego123
    volumes:
      - ./mongo_data:/data/db